### ISSUE TITLE
Storing trained objects for reuse in .predict() statements

### ISSUE THREAD

**Issue by hhegre** [prio-data/views_runs#2] opened 2021-11-30 09:16 UTC
This is a feature I raised a year ago or so, but has not been followed up. 

Training models across a number of steps can be fairly slow, so it would be useful to avoid retraining. Below is some example code using views_runs. The way this is currently set up, I would have to restrain for all steps if I wanted to add steps, for instance. It would have been useful to pickle the trained objects and add a test to the views_runs class so that an identical trained object can be retrieved rather than retrained. 

This would be even more important when we get to setting ViEWS3 in production. For a production run, I don't think we should retrain, just retrieve pickles and updated data and do the predictions.

There has to be a test that the model exists, i.e. testing that it is the correct step, ML algorithm, dependent variable, set of columns, time ranges, etc. These, however, are metadata that we would like to store in any case for documentation purposes?

steps = [1,2,3,6,12,18,24]
calib_partitioner =  views_runs.DataPartitioner({"A":{"train":(121,408),"test":(409,444)}})
model = views_runs.StepshiftedModels(RandomForestRegressor(),steps, 'lngedbest')
run_calib = views_runs.ViewsRun(calib_partitioner,models)
run_calib.fit("A","train",dataset)

**Comment by hhegre** [comment] 2021-11-30 09:18
@Peder2911 : I am for some reason unable to set assignee or project for this issue

**Comment by Peder2911** [comment] 2021-11-30 10:46
It is not fair to say that this has not been followed up, because the work I've done on the views_run class is prerequisite to being able to serialize an object like this.

Should be fairly easy to implement, I was considering asking someone else on the team to write a `.dump` and `.load` method, first just testing whether or not this can be done by simply `pickle.dump`ing the object. Do you know whether or not anyone on the team has the capacity to look at this?

**Comment by Peder2911** [comment] 2021-11-30 10:47
This issue is a duplicate of https://github.com/prio-data/views_runs/issues/1, but since you've written a bit more here than I did, I'll close the other one.

**Comment by Peder2911** [comment] 2021-11-30 11:27
Relates to https://github.com/prio-data/stepshift/issues/5

**Comment by Peder2911** [comment] 2021-11-30 14:21
I just closed my current issue, could start work on this tomorrow. Prioritize @hhegre ?

**Comment by hhegre** [comment] 2021-11-30 16:34
Prioritization depends a bit on the status of other things, but given that the LOA issue seems to be under control and @jimdale  and @mihaicroicu are working on the two major system revisions we have identified, this might be sufficiently important at this point. Also, this touches upon metadata for models which is closely linked to how we store predictions, another issue that has priority.

**Comment by Peder2911** [comment] 2021-12-01 08:04
I am handling a pull request that should resolve  a LOA problem that Mihai raised yesterday, other than that I think we have solved our LOA woes for now.

**Comment by Peder2911** [comment] 2021-12-01 13:27
@hhegre @jimdale @mihaicroicu considering metadata related to model objects; what would be interesting to keep? Author? Trained @ date? In addition to the algorithm + parameters / timespan.

**Comment by Peder2911** [comment] 2021-12-01 13:29
Depending on the storage scheme we choose, this could be very easy or more complicated to change down the line.

**Comment by hhegre** [comment] 2021-12-01 15:15
Author, date of run is absolutely useful.

Also:
Model name(s)
Queryset used? Data retrieval date? 
List of columns would also be useful (might not be identical to columns from the queryset...)
And clear specification of what the dependent variable is
Maybe even the script used to produce the model (i.e. the GitHub location for the script)

**Comment by Peder2911** [comment] 2021-12-01 15:39
Good! All of these could be implemented, starting with a Pydantic model, and then through some sort of storage once we get to that. Further suggestions @mihaicroicu , @jimdale ?

**Comment by Peder2911** [comment] 2021-12-02 13:05
Could you elaborate a bit with regards to "a clear specification of the dependent variable", do you mean a fulltext description, or just a reference?

**Comment by hhegre** [comment] 2021-12-02 13:19
Specifying the column name and including the column in the prediction file should be sufficient. If there is an associated queryset we have almost complete information. What might be useful but could be more difficult to specify is cases where there has been transformations to it. But as long as we have a copy of it we can at least compare with the output of the queryset.

**Comment by Peder2911** [comment] 2021-12-02 13:20
Indeed, and the user might of course apply local transforms, or alter the data in other ways. Letting the user include a script link is a good idea, that at least increases the chance of successful reproduction.

**Comment by Peder2911** [comment] 2022-01-11 10:40
This is now implemented via the

**Comment by Peder2911** [comment] 2022-01-11 10:40
This is now implemented via the functions in the storage module.
Closing!

**Closed as completed by Peder2911** 2022-01-11 10:40 UTC
